### ISSUE TITLE
tunnel won't go up on v1.4

### ISSUE THREAD

**Issue by privjimmie** [w35l3y/hassio-addons#15]
After updating to v1.4, the tunnel stopped working, and this is the output log

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/cloudflare.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/cloudflare.sh: Permission denied
cont-init: info: /etc/cont-init.d/cloudflare.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by sheminasalam** [comment]
same issue

**Comment by maverik80** [comment]
same exact mistake, the tunnel is no longer created

**Comment by w35l3y** [comment]
Sorry, I forgot I had pushed an work in progress and went to sleep.
I thought I only had commited.
I will update it as soon as I wake up.

**Comment by w35l3y** [comment]
I disabled apparmor temporarily, but I am still looking for definitive solution.
You may try 1.4.1 for now.
I tested it locally and it is working as expected.

**Comment by karolk2k22** [comment]
thanks @w35l3y but in the plugin panel only version 1.4.0 is available, how upgrade to 1.4.1. hmmm

**Comment by w35l3y** [comment]
You may wait until HA check for update or go to Add-on Store and check for update yourself by clicking on the "..." at right upper corner and then "Check for updates".
![image](https://user-images.githubusercontent.com/963510/168423366-367e382f-b052-4a17-b0fa-049aed42df57.png)

**Comment by mdanilohome** [comment]
I'm having the same problem after updating Cloudflare to version 1.4.0.
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/cloudflare.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/cloudflare.sh: Permission denied
cont-init: info: /etc/cont-init.d/cloudflare.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by maverik80** [comment]
> You may wait until HA check for update automatically or go to Add-on Store and check for update yourself by clicking on the "..." at right upper corner and then "Check for updates". ![image](https://user-images.githubusercontent.com/963510/168423366-367e382f-b052-4a17-b0fa-049aed42df57.png)

even checking for updates it still doesn't show up, I'll wait ... I'll test and tell you

**Comment by w35l3y** [comment]
> I'm having the same problem after updating Cloudflare to version 1.4.0.

I don't seem it was updated.
Are you sure you are using 1.4.1 ?

**Comment by karolk2k22** [comment]
the update is only available as a new repository
![Screenshot_20](https://user-images.githubusercontent.com/105540765/168423565-3dec2e86-9253-4d14-af07-a1842de07519.png)

**Comment by w35l3y** [comment]
I also had to modify slug from `cloudflare-tunnel` to `cloudflare_tunnel`
That is why it shows up twice.
It should disappear at some point.

**Comment by karolk2k22** [comment]
ok :)

**Comment by mdanilohome** [comment]
@karolk2k22 , hello, if you have run uninstall version 1.4.0 and installed version 1.4.1 and it works, please report here. Thanks.

**Comment by sheminasalam** [comment]
you dont have to run uninstall 1.40 for 1.41 to work. You can just stop the 1.40 and then run 1.41. that how I did it

**Comment by w35l3y** [comment]
You are right when the slug is the same.
When the slug is different, they are considered 2 separate add-ons.

**Comment by maverik80** [comment]
the beloved testing, the log now says to leave the cloudflare page open to download the certificate but this is not the case and therefore an error on the argo tunnel

**Comment by mdanilohome** [comment]
t still doesn't work, now with another error message as mentioned in the @maverik80 .

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
fix-attrs: info: applying /etc/fix-attrs.d/permissions
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/cloudflare.sh
Validating rules from /data/options.json
OK
/root/.cloudflared:
options.json
Please open the following URL and log in with your Cloudflare account:

https://dash.cloudflare.com/argotunnel?callback=https%3A%2F%2Flogin.cloudflareaccess.org%2Fsj-6OnSxwhy73M1ldl2Hr6yS6g4WqjbVlfIBLKp1og0%3D

Leave cloudflared running to download the cert automatically.
2022-05-14T11:51:57Z INF Waiting for login...
2022-05-14T11:52:52Z INF Waiting for login...
2022-05-14T11:53:48Z INF Waiting for login...
2022-05-14T11:54:43Z INF Waiting for login...
2022-05-14T11:55:39Z INF Waiting for login...
2022-05-14T11:56:34Z INF Waiting for login...
2022-05-14T11:57:29Z INF Waiting for login...
2022-05-14T11:58:25Z INF Waiting for login...
2022-05-14T11:59:20Z INF Waiting for login...
2022-05-14T12:00:15Z INF Waiting for login...
Failed to write the certificate due to the following error:
Failed to fetch resource

Your browser will download the certificate instead. You will have to manually
copy it to the following path:

/root/.cloudflared/cert.pem
Failed to fetch resource
cont-init: info: /etc/cont-init.d/cloudflare.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by w35l3y** [comment]
Did you open the url and authorized again ?

**Comment by karolk2k22** [comment]
@mdanilohome the same add-on under the same/similar name. Inside is new wersion 1.4.1

**Comment by w35l3y** [comment]
[Cloudflare Tunnel](https://my.home-assistant.io/redirect/supervisor_addon/?addon=c50d1fa4_cloudflare_tunnel&repository_url=https%3A%2F%2Fgithub.com%2Fw35l3y%2Fhassio-addons)

**Comment by karolk2k22** [comment]
@mdanilohome
> Please open the following URL and log in with your Cloudflare account:
> 
> https://dash.cloudflare.com/argotunnel?callback=https%3A%2F%2Flogin.cloudflareaccess.org%2Fsj-6OnSxwhy73M1ldl2Hr6yS6g4WqjbVlfIBLKp1og0%3D

**Comment by mdanilohome** [comment]
I opened cloudflare account from the URL and updated the certificate. Everything working now. Thanks @w35l3y  and @karolk2k22 .

**Comment by w35l3y** [comment]
Due to recent modifications on [s6-overlay](https://github.com/just-containers/s6-overlay), I had to:
* Modify some files permissions
* Add `"init": false,`
* Add `"apparmor": true,`

And due to a limitation on the `Apparmor`, I had to:
* Change from `"slug": "cloudflare-tunnel",` to `"slug": "cloudflare_tunnel",`

It makes the add-on show up as being a new one and prevents the normal process of updating from an older version to newer.

So, that is the reason why you will need to install the "new" add-on and follow the whole process of authenticating/authorizing again.

My recommendation is:
1. Stop older version (1.4.0)
2. Copy configuration yaml from the older version
3. Install newer version (currently, 1.5.0)
4. Paste configuration yaml to the newer version
5. Start newer version and follow the step "Start the addon and go to tab Log" as stated in the [README](https://github.com/w35l3y/hassio-addons/tree/main/cloudflare_tunnel#how-to-use-it)
6. Uninstall older version

There are still having some discussions here:
* [Hello_world example addon from developer docs stopped working (s6 overlay issue?)](https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486/6?u=w35l3y)

**Comment by privjimmie** [comment]
Thank you @w35l3y, its up and running again on 1.5
Thank you for all your work on this addon. It really is a great feature!!
